# Generated by Django 2.2.12 on 2020-05-01 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('department', models.CharField(blank=True, default='', max_length=50)),
                ('grade', models.CharField(blank=True, default='', max_length=50)),
                ('gender', models.BooleanField(default=True)),
                ('contact', models.CharField(blank=True, default='', max_length=50)),
                ('communities', models.ManyToManyField(blank=True, default=[], related_name='user', to='market.Community')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='goods')),
                ('name', models.CharField(default='null', max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('publish_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('sold_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buy', to='market.User')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='market.Category')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sell', to='market.User')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('publish_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('publisher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publish', to='market.User')),
            ],
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.Post')),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic', to='market.User')),
            ],
            bases=('market.post',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.Post')),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='market.Product')),
            ],
            bases=('market.post',),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='market.Post')),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='market.Community')),
            ],
            bases=('market.post',),
        ),
    ]
