# Generated by Django 3.0.3 on 2020-05-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamic',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
