# Generated by Django 2.2.12 on 2020-05-01 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AlterField(
            model_name='chat',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='market.Community'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='market.Product'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic', to='market.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publisher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publish', to='market.User'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buyer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy', to='market.User'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell', to='market.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='user', to='market.Community'),
        ),
    ]
