# Generated by Django 2.2.12 on 2020-05-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200501_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
