# Generated by Django 3.0.6 on 2020-05-25 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0002_auto_20200524_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_to_goods',
            name='belong',
        ),
        migrations.RemoveField(
            model_name='comment_to_goods',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='product',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='user',
            name='communities',
        ),
        migrations.RemoveField(
            model_name='user',
            name='owner',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterField(
            model_name='comment',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publish_dynamic_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publish_dynamic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Comment_To_Goods',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='USER',
        ),
    ]
