# Generated by Django 3.0.6 on 2020-05-25 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20200525_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamic',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='belong_set', to='market.Category'),
        ),
    ]
