# Generated by Django 2.2.12 on 2020-05-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('大一', '大一'), ('大二', '大二'), ('大三', '大三'), ('大四', '大四'), ('研究生', '研究生'), ('其他', '其他')], default='其他', max_length=50),
        ),
    ]
